apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: military-app
type: Opaque
data:
  # À générer avec: echo -n 'valeur' | base64
  # IMPORTANT: Ne jamais commiter ce fichier avec de vraies valeurs en clair
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: Y2hhbmdlLW1vaS1lbi1wcm9kdWN0aW9u
  JWT_SECRET: Y2hhbmdlLW1vaS1hdXNzaS1lbi1wcm9kdWN0aW9uLWF2ZWMtb3BlbnNzbC1yYW5kLWJhc2U2NC02NA==
  MAIL_USERNAME: Y2hhbmdlLW1vaS1hdXNzaQ==
  MAIL_PASSWORD: Y2hhbmdlLW1vaS1hdXNzaQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: military-app
type: Opaque
stringData:
  # Ce Secret utilise stringData pour ne pas avoir à encoder en base64 manuellement
  # Kubernetes encode automatiquement
  # À remplacer par de vraies valeurs avant déploiement
  JWT_SECRET: "remplacer-par-vrai-secret-64-caracteres-min"
  MAIL_PASSWORD: "remplacer-par-vrai-mot-de-passe"